# Join Lowest MAE score Data

In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings("ignore") 

df1 = pd.read_csv('../scores/handle_time_score.csv')
df2 = pd.read_csv('../scores/volume_score.csv')
df3 = pd.read_csv('../scores/aht_score.csv')

df1['diff'] = (df1['old'] - df1['prophet'])
df2['diff'] = df2['old'] - df2['prophet']
df3['diff'] = df3['old'] - df3['prophet']

df = pd.concat([df1,df2,df3],0)

df.rename(columns={'Unnamed: 0': 'bu'}, inplace=True)
df.index = range(df.shape[0])
display(df)

,bu,old,prophet,kpi,start_train,end_train,diff
0,BRO-Co,22645.600000,12824.051244,handle_time,2018-10-01,2020-12-04,9821.548756
1,RIS_ah,402731.875000,55038.592073,handle_time,2019-11-01,2020-12-01,347693.282927
2,BRO_ah,35353.400000,12555.028776,handle_time,2018-11-01,2020-12-04,22798.371224
3,CS-Mar,20754.125000,31942.657384,handle_time,2017-11-01,2020-12-01,-11188.532384
4,PSG_ah,279187.000000,25004.863611,handle_time,2019-11-01,2020-12-04,254182.136389
5,CS-Joh,17810.600000,43606.769055,handle_time,2019-12-01,2020-12-04,-25796.169055
6,CS-Nat,15103.750000,6595.163425,handle_time,2016-11-01,2020-12-01,8508.586575
7,CS-Ala,7169.000000,2799.627294,handle_time,2016-01-01,2020-12-01,4369.372706
8,WISE-C,475344.200000,251570.959285,handle_time,2016-11-01,2020-12-04,223773.240715
9,RCS-PH,60709.750000,23331.358339,handle_time,2018-11-01,2020-12-01,37378.391661
10,BRO-Co,19.800000,25.678613,volume,2018-10-01,2020-12-04,-5.878613
11,BRO_ah,66.400000,23.369721,volume,2018-11-01,2020-12-04,43.030279
12,PSG_ah,188.000000,96.060536,volume,2019-11-01,2020-12-01,91.939464
13,CS-Nat,23.875000,8.819848,volume,2016-11-01,2020-12-01,15.055152
14,CS-Ala,7.500000,3.296964,volume,2016-01-01,2020-12-01,4.203036
15,RIS_ah,175.000000,143.049391,volume,2019-11-01,2020-12-01,31.950609
16,CS-Mar,21.600000,42.312165,volume,2017-11-01,2020-12-04,-20.712165
17,WISE-C,358.200000,349.545144,volume,2016-11-01,2020-12-04,8.654856
18,RCS-PH,75.000000,52.096511,volume,2018-11-01,2020-12-01,22.903489
19,CS-Joh,30.200000,73.760608,volume,2019-12-01,2020-12-04,-43.560608
20,BRO-Co,99.960792,52.775263,aht,2018-10-01,2020-12-04,47.185529
21,CS-Ala,89.310284,39.688675,aht,2016-01-01,2020-12-04,49.621608
22,CS-Mar,41.749555,13.410964,aht,2017-11-01,2020-12-04,28.338592
23,RCS-PH,26.523627,39.091396,aht,2018-11-01,2020-12-01,-12.567769
24,PSG_ah,89.213309,45.920512,aht,2019-11-01,2020-12-04,43.292797
25,RIS_ah,130.388847,36.431798,aht,2019-11-01,2020-12-01,93.957049
26,CS-Nat,104.350778,48.764443,aht,2016-11-01,2020-12-01,55.586334
27,CS-Joh,29.140417,24.979869,aht,2019-12-01,2020-12-04,4.160547
28,BRO_ah,32.189043,27.989019,aht,2018-11-01,2020-12-01,4.200024
29,WISE-C,37.329178,9.156926,aht,2016-11-01,2020-12-04,28.172252

# `diff` is the difference between old and new model Mean Absolute Error (MAE) for recent test periods.

In [12]:
# only consider better MAE than old model
diff = df[df['diff']>0]
neg = df[~(df['diff']>0)]
diff = diff.sort_values(by=['kpi','diff'])
neg = neg.sort_values(by=['kpi','diff'])

display(diff)
diff.to_csv('../scores/model_results_'+diff['end_train'].values[0]+'.csv', index=False)

,bu,old,prophet,kpi,start_train,end_train,diff
27,CS-Joh,29.140417,24.979869,aht,2019-12-01,2020-12-04,4.160547
28,BRO_ah,32.189043,27.989019,aht,2018-11-01,2020-12-01,4.200024
29,WISE-C,37.329178,9.156926,aht,2016-11-01,2020-12-04,28.172252
22,CS-Mar,41.749555,13.410964,aht,2017-11-01,2020-12-04,28.338592
24,PSG_ah,89.213309,45.920512,aht,2019-11-01,2020-12-04,43.292797
20,BRO-Co,99.960792,52.775263,aht,2018-10-01,2020-12-04,47.185529
21,CS-Ala,89.310284,39.688675,aht,2016-01-01,2020-12-04,49.621608
26,CS-Nat,104.350778,48.764443,aht,2016-11-01,2020-12-01,55.586334
25,RIS_ah,130.388847,36.431798,aht,2019-11-01,2020-12-01,93.957049
7,CS-Ala,7169.000000,2799.627294,handle_time,2016-01-01,2020-12-01,4369.372706
6,CS-Nat,15103.750000,6595.163425,handle_time,2016-11-01,2020-12-01,8508.586575
0,BRO-Co,22645.600000,12824.051244,handle_time,2018-10-01,2020-12-04,9821.548756
2,BRO_ah,35353.400000,12555.028776,handle_time,2018-11-01,2020-12-04,22798.371224
9,RCS-PH,60709.750000,23331.358339,handle_time,2018-11-01,2020-12-01,37378.391661
8,WISE-C,475344.200000,251570.959285,handle_time,2016-11-01,2020-12-04,223773.240715
4,PSG_ah,279187.000000,25004.863611,handle_time,2019-11-01,2020-12-04,254182.136389
1,RIS_ah,402731.875000,55038.592073,handle_time,2019-11-01,2020-12-01,347693.282927
14,CS-Ala,7.500000,3.296964,volume,2016-01-01,2020-12-01,4.203036
17,WISE-C,358.200000,349.545144,volume,2016-11-01,2020-12-04,8.654856
13,CS-Nat,23.875000,8.819848,volume,2016-11-01,2020-12-01,15.055152
18,RCS-PH,75.000000,52.096511,volume,2018-11-01,2020-12-01,22.903489
15,RIS_ah,175.000000,143.049391,volume,2019-11-01,2020-12-01,31.950609
11,BRO_ah,66.400000,23.369721,volume,2018-11-01,2020-12-04,43.030279
12,PSG_ah,188.000000,96.060536,volume,2019-11-01,2020-12-01,91.939464

# Explore negative model results

In [13]:
neg

,bu,old,prophet,kpi,start_train,end_train,diff
23,RCS-PH,26.523627,39.091396,aht,2018-11-01,2020-12-01,-12.567769
5,CS-Joh,17810.600000,43606.769055,handle_time,2019-12-01,2020-12-04,-25796.169055
3,CS-Mar,20754.125000,31942.657384,handle_time,2017-11-01,2020-12-01,-11188.532384
19,CS-Joh,30.200000,73.760608,volume,2019-12-01,2020-12-04,-43.560608
16,CS-Mar,21.600000,42.312165,volume,2017-11-01,2020-12-04,-20.712165
10,BRO-Co,19.800000,25.678613,volume,2018-10-01,2020-12-04,-5.878613

# Calculate cost savings since end of training

In [14]:
for kpi in ['handle_time', 'volume', 'aht']:
    if kpi == 'handle_time':
        hours_saved = diff.loc[df['kpi']==kpi]['diff'].sum()/3600
    elif kpi == 'volume':
        hours_saved = diff.loc[df['kpi']==kpi]['diff'].sum()/8.3
    else:   
        hours_saved = diff.loc[df['kpi']==kpi]['diff'].sum()/60

    print('\nDaily '+kpi+' Saved:',round(hours_saved,1))
    print('Annual Savings:',"${:,.2f}".format(hours_saved *262* 25))

Daily handle_time Saved: 252.4
Annual Savings: $1,653,010.64

Daily volume Saved: 26.2
Annual Savings: $171,828.51

Daily aht Saved: 5.9
Annual Savings: $38,701.19

# Visualize cost savings with Google Data Studio
by kpi breakdown by business unit

In [117]:
%%html

<iframe width="600" height="450" 
src="https://datastudio.google.com/embed/reporting/9d1e6d34-e57a-4930-8369-bce46555eaf4/page/aXLqB" 
frameborder="0" style="border:0" allowfullscreen></iframe>